// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: enhancements.sql

package db

import (
	"context"
)

const getEnhancements = `-- name: GetEnhancements :many
SELECT id, faction_id, name, cost, detachment, legend, description, field8 FROM enhancements
`

func (q *Queries) GetEnhancements(ctx context.Context) ([]Enhancement, error) {
	rows, err := q.db.QueryContext(ctx, getEnhancements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enhancement
	for rows.Next() {
		var i Enhancement
		if err := rows.Scan(
			&i.ID,
			&i.FactionID,
			&i.Name,
			&i.Cost,
			&i.Detachment,
			&i.Legend,
			&i.Description,
			&i.Field8,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
