// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: factions.sql

package db

import (
	"context"
)

const getFaction = `-- name: GetFaction :one
SELECT id, name, faction_id FROM faction
WHERE faction.id = $1
`

func (q *Queries) GetFaction(ctx context.Context, id int32) (Faction, error) {
	row := q.db.QueryRowContext(ctx, getFaction, id)
	var i Faction
	err := row.Scan(&i.ID, &i.Name, &i.FactionID)
	return i, err
}
