// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: models.sql

package db

import (
	"context"
	"database/sql"
)

const createModel = `-- name: CreateModel :exec
INSERT INTO models (old_id, datasheet_id, name, M, T, Sv, inv_sv, W, Ld, OC)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type CreateModelParams struct {
	OldID       int32
	DatasheetID int32
	Name        string
	M           string
	T           string
	Sv          string
	InvSv       string
	W           int32
	Ld          string
	Oc          int32
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) error {
	_, err := q.db.ExecContext(ctx, createModel,
		arg.OldID,
		arg.DatasheetID,
		arg.Name,
		arg.M,
		arg.T,
		arg.Sv,
		arg.InvSv,
		arg.W,
		arg.Ld,
		arg.Oc,
	)
	return err
}

const getModel = `-- name: GetModel :one
SELECT old_id, datasheet_id, name, m, t, sv, inv_sv, w, ld, oc FROM models
WHERE datasheet_id = $1
`

func (q *Queries) GetModel(ctx context.Context, datasheetID int32) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModel, datasheetID)
	var i Model
	err := row.Scan(
		&i.OldID,
		&i.DatasheetID,
		&i.Name,
		&i.M,
		&i.T,
		&i.Sv,
		&i.InvSv,
		&i.W,
		&i.Ld,
		&i.Oc,
	)
	return i, err
}

const getModelsForFaction = `-- name: GetModelsForFaction :many
SELECT models.old_id, models.datasheet_id, models.name, models.m, models.t, models.sv, models.inv_sv, models.w, models.ld, models.oc FROM models
JOIN faction ON models.datasheet_id = faction.id
WHERE faction.faction_id = $1
`

func (q *Queries) GetModelsForFaction(ctx context.Context, factionID sql.NullString) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, getModelsForFaction, factionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.OldID,
			&i.DatasheetID,
			&i.Name,
			&i.M,
			&i.T,
			&i.Sv,
			&i.InvSv,
			&i.W,
			&i.Ld,
			&i.Oc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModel = `-- name: UpdateModel :one
UPDATE models
SET
  old_id = $2,
  name = $3,
  M = $4,
  T = $5,
  W = $6,
  Sv = $7,
  inv_sv = $8,
  Ld = $9,
  OC = $10
WHERE datasheet_id = $1
RETURNING old_id, datasheet_id, name, m, t, sv, inv_sv, w, ld, oc
`

type UpdateModelParams struct {
	DatasheetID int32
	OldID       int32
	Name        string
	M           string
	T           string
	W           int32
	Sv          string
	InvSv       string
	Ld          string
	Oc          int32
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, updateModel,
		arg.DatasheetID,
		arg.OldID,
		arg.Name,
		arg.M,
		arg.T,
		arg.W,
		arg.Sv,
		arg.InvSv,
		arg.Ld,
		arg.Oc,
	)
	var i Model
	err := row.Scan(
		&i.OldID,
		&i.DatasheetID,
		&i.Name,
		&i.M,
		&i.T,
		&i.Sv,
		&i.InvSv,
		&i.W,
		&i.Ld,
		&i.Oc,
	)
	return i, err
}
