// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Ability struct {
	DatasheetID int32
	Line        int32
	AbilityID   int32
	Model       string
	Name        string
	Description string
	Type        string
	Parameter   string
}

type Enhancement struct {
	ID          int32
	FactionID   string
	Name        string
	Cost        int32
	Detachment  string
	Legend      string
	Description string
	Field8      string
}

type Faction struct {
	ID        int32
	Name      sql.NullString
	FactionID sql.NullString
}

type Keyword struct {
	ID          int32
	DatasheetID int32
	Keyword     string
}

type Model struct {
	OldID       int32
	DatasheetID int32
	Name        string
	M           string
	T           string
	Sv          string
	InvSv       string
	W           int32
	Ld          string
	Oc          int32
}

type Point struct {
	ID          int32
	DatasheetID int32
	Line        int32
	Description string
	Cost        int32
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt sql.NullTime
}

type Roster struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ArmyList     json.RawMessage
	Enhancements []string
	Name         string
	Faction      string
}

type User struct {
	ID             uuid.UUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Username       string
	HashedPassword string
	IsAdmin        bool
}

type Wargear struct {
	DatasheetID int32
	ID          int32
	Name        string
	Range       string
	Type        string
	A           string
	BsWs        string
	Strength    string
	Ap          sql.NullInt32
	Damage      string
}

type Wargeardescription struct {
	ID          int32
	DatasheetID int32
	Line        int32
	Name        string
	Description string
}
