// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Faction struct {
	ID        sql.NullString
	Name      sql.NullString
	FactionID sql.NullString
}

type Model struct {
	OldID       sql.NullInt32
	DatasheetID string
	Name        string
	M           string
	T           int32
	Sv          sql.NullString
	InvSv       sql.NullString
	W           sql.NullInt32
	Ld          sql.NullString
	Oc          sql.NullString
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Username       string
	HashedPassword sql.NullString
	IsAdmin        bool
}

type Wargear struct {
	DatasheetID int32
	ID          int32
	Name        string
	Range       sql.NullString
	Type        sql.NullString
	A           sql.NullString
	BsWs        sql.NullString
	Strength    sql.NullString
	Ap          sql.NullString
	Damage      sql.NullString
}
