// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wargearDescriptions.sql

package db

import (
	"context"
)

const getWargearDescriptions = `-- name: GetWargearDescriptions :many
SELECT id, datasheet_id, line, name, description FROM wargearDescription
WHERE datasheet_id = $1
`

func (q *Queries) GetWargearDescriptions(ctx context.Context, datasheetID int32) ([]Wargeardescription, error) {
	rows, err := q.db.QueryContext(ctx, getWargearDescriptions, datasheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wargeardescription
	for rows.Next() {
		var i Wargeardescription
		if err := rows.Scan(
			&i.ID,
			&i.DatasheetID,
			&i.Line,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
